=== PEDROMIRAS/DAW/Lenguaje de marcas/Tema 3/EJ_Propuestos/ej14Enium.xsd
<?xml version="1.1" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="empresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="empleado" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="apellido" type="xs:string"/>
                            <xs:element name="fechaNacimiento" type="xs:date"/>
                            <xs:element name="salario" type="xs:decimal"/>
                            <xs:element name="activo" type="xs:boolean"/>
                            <xs:element name="horaEntrada" type="xs:time"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:integer"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="nombreEmpresa" type="xs:string"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== PEDROMIRAS/DAW/Lenguaje de marcas/Tema 3/EJ_Propuestos/ej14EniumXSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<empresa nombreEmpresa = "TechCorp" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="ej14Enium.xsd">
    <empleado id="1">
        <nombre>John</nombre>
        <apellido>Doe</apellido>
        <fechaNacimiento>1990-05-15</fechaNacimiento>
        <salario>50000.00</salario>
        <activo>true</activo>
        <horaEntrada>09:00:00</horaEntrada>
    </empleado>
    <empleado id="2">
        <nombre>Jane</nombre>
        <apellido>Smith</apellido>
        <fechaNacimiento>1995-07-20</fechaNacimiento>
        <salario>60000.00</salario>
        <activo>false</activo>
        <horaEntrada>09:00:00</horaEntrada>
    </empleado>
</empresa>
