=== PEDROMIRAS/DAW/Lenguaje de marcas/Tema 3/EJ_Propuestos/ej21Enium.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="programming_library">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="language" minOccurs="3" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="name" type="xs:string"/>
                        <xs:element name="creator" type="xs:string"/>
                        <xs:element name="year_created" type="xs:integer"/>
                        <xs:element name="description" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== PEDROMIRAS/DAW/Lenguaje de marcas/Tema 3/EJ_Propuestos/ej21EniumXSD.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<programming_library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="ej21Enium.xsd">
    <language>
        <name>Python</name>
        <creator>Guido van Rossum</creator>
        <year_created>1991</year_created>
        <description>Python is an interpreted, high-level, general-purpose programming language.</description>
    </language>
    <language>
        <name>Java</name>
        <creator>James Gosling</creator>
        <year_created>1995</year_created>
        <description>Java is a class-based, object-oriented programming language.</description>
    </language>
    <language>
        <name>JavaScript</name>
        <creator>Brendan Eich</creator>
        <year_created>1995</year_created>
        <description>JavaScript is a high-level, interpreted programming language.</description>
    </language>
</programming_library>
