=== PEDROMIRAS/DAW/Lenguaje de marcas/Tema 3/EJ_Propuestos/ej23Enium.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="hardwareCatalog">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="item" minOccurs="5" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:integer"/>
                            <xs:element name="type" type="xs:string"/>
                            <xs:element name="brand" type="xs:string"/>
                            <xs:element name="model" type="xs:string"/>
                            <xs:element name="specifications" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== PEDROMIRAS/DAW/Lenguaje de marcas/Tema 3/EJ_Propuestos/ej23EniumXSD.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<hardwareCatalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ej23Enium.xsd">
    <item>
        <id>1</id>
        <type>Processor</type>
        <brand>Intel</brand>
        <model>Core i7-9700K</model>
        <specifications>8-Core, 3.6 GHz</specifications>
    </item>
    <item>
        <id>2</id>
        <type>RAM</type>
        <brand>Corsair</brand>
        <model>Vengeance LPX 16GB</model>
        <specifications>DDR4, 3200MHz</specifications>
    </item>
    <item>
        <id>3</id>
        <type>Graphics Card</type>
        <brand>NVIDIA</brand>
        <model>GeForce RTX 3080</model>
        <specifications>10GB GDDR6X</specifications>
    </item>
    <item>
        <id>4</id>
        <type>Hard Drive</type>
        <brand>Western Digital</brand>
        <model>WD Blue 1TB</model>
        <specifications>SATA, 7200 RPM</specifications>
    </item>
    <item>
        <id>5</id>
        <type>Motherboard</type>
        <brand>ASUS</brand>
        <model>ROG Strix Z390-E</model>
        <specifications>Socket LGA1151, ATX</specifications>
    </item>
</hardwareCatalog>
