=== PEDROMIRAS/DAW/Lenguaje de marcas/Tema 3/EJ_Propuestos/estudiantes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="universidad">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="estudiante" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="apellido" type="xs:string"/>
                            <xs:element name="edad" type="xs:integer"/>
                            <xs:element name="carrera" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== PEDROMIRAS/DAW/Lenguaje de marcas/Tema 3/EJ_Propuestos/estudiantes.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<universidad xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="estudiantes.xsd">
    <estudiante>
        <nombre>Carlos</nombre>
        <apellido>Alonso</apellido>
        <edad>22</edad>
        <carrera>Informática</carrera>
    </estudiante>
    <estudiante>
        <nombre>María</nombre>
        <apellido>García</apellido>
        <edad>21</edad>
        <carrera>Telecomunicaciones</carrera>
    </estudiante>
    <estudiante>
        <nombre>Juan</nombre>
        <apellido>Pérez</apellido>
        <edad>23</edad>
        <carrera>Mecanica</carrera>
    </estudiante>
</universidad>
